google-modules: usb: dwc3: Fix DWC3_LLUCTL conflict
Resolves the following compilation error:
In file included from /home/trijal/Builds/neutrino_kernel_google_caimito/google-modules/display/samsung/cal_common/dp_cal.h:17,
                 from /home/trijal/Builds/neutrino_kernel_google_caimito/google-modules/display/samsung/cal_9865/dp_reg.c:15:
/home/trijal/Builds/neutrino_kernel_google_caimito/google-modules/soc/gs/include/linux/usb/dwc3-exynos.h:30:9: error: "DWC3_LLUCTL" redefined [-Werror]
   30 | #define DWC3_LLUCTL             0xd024
      |         ^~~~~~~~~~~
In file included from /home/trijal/Builds/neutrino_kernel_google_caimito/google-modules/soc/gs/include/linux/usb/dwc3-exynos.h:23:
/home/trijal/Builds/neutrino_kernel_google_caimito/drivers/usb/dwc3/core.h:183:9: note: this is the location of the previous definition
  183 | #define DWC3_LLUCTL(n)          (0xd024 + ((n) * 0x80))
      |         ^~~~~~~~~~~
cc1: all warnings being treated as errors
make[4]: *** [/home/trijal/Builds/neutrino_kernel_google_caimito/scripts/Makefile.build:289: google-modules/display/samsung/cal_9865/dp_reg.o] Error 1
make[3]: *** [/home/trijal/Builds/neutrino_kernel_google_caimito/scripts/Makefile.build:543: google-modules/display/samsung] Error 2
make[3]: *** Waiting for unfinished jobs....